import * as React from "react";
import { Button, Skeleton } from "@/components/ui";
import "./states.css";

type Action={label:string;onClick?:()=>void;href?:string;variant?:"primary"|"secondary"|"ghost"|"danger"};
function StateShell({icon,title,description,actions=[],className=""}:{icon?:React.ReactNode;title:string;description?:React.ReactNode;actions?:Action[];className?:string}){return <section className={`rwa-state ${className}`}>{icon&&<div className="rwa-state__icon" aria-hidden="true">{icon}</div>}<h2 className="rwa-state__title">{title}</h2>{description&&<div className="rwa-state__description">{description}</div>}{actions.length>0&&<div className="rwa-state__actions">{actions.map(a=>a.href?<a key={a.label} href={a.href}><Button variant={a.variant??"primary"}>{a.label}</Button></a>:<Button key={a.label} variant={a.variant??"primary"} onClick={a.onClick}>{a.label}</Button>)}</div>}</section>}

export function EmptyState({title="Nothing here yet",description="There is no data to show yet.",actions=[]}:{title?:string;description?:React.ReactNode;actions?:Action[]}){return <StateShell icon="○" title={title} description={description} actions={actions} className="rwa-empty-state"/>}
export function ErrorState({title="Something went wrong",description="We couldn’t load this section. Try again.",actions=[]}:{title?:string;description?:React.ReactNode;actions?:Action[]}){return <StateShell icon="!" title={title} description={description} actions={actions} className="rwa-error-state"/>}
export function PermissionState({title="Access restricted",description="You don’t currently have permission to perform this action.",actions=[],tone="warning"}:{title?:string;description?:React.ReactNode;actions?:Action[];tone?:"warning"|"purple"}){return <div data-tone={tone}><StateShell icon="◇" title={title} description={description} actions={actions} className="rwa-permission-state"/></div>}
export function LoadingState({rows=4}:{rows?:number}){return <section className="rwa-loading-state" aria-busy="true" aria-label="Loading"><Skeleton width="38%" height={24}/><Skeleton width="65%" height={14}/><div className="rwa-loading-state__grid">{Array.from({length:rows}).map((_,i)=><div className="rwa-loading-card" key={i}><Skeleton width="44%" height={14}/><Skeleton width="72%" height={28}/><Skeleton width="100%" height={12}/></div>)}</div></section>}
